platform :ios, '10.0'
use_frameworks!

target 'appnews' do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 3.0'
  pod 'Alamofire', '~> 4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end
